apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kong-gateway
  namespace: argocd
spec:
  destination:
    namespace: kong
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/KeyssonG/Kong-Gateway.git
    path: k8s/
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
