apiVersion: apps/v1
kind: Deployment
metadata:
  name: kong
  labels:
    app: kong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kong
  template:
    metadata:
      labels:
        app: kong
    spec:
      containers:
        - name: kong
          image: kong:3.7
          ports:
            - containerPort: 8000
            - containerPort: 8443
            - containerPort: 8001
            - containerPort: 8444
            - containerPort: 8002
            - containerPort: 8445
            - containerPort: 8003
            - containerPort: 8004
          env:
            - name: KONG_DATABASE
              value: "off"  # Alterado para "off" para habilitar o modo DB-less.
            - name: KONG_DECLARATIVE_CONFIG
              value: "/kong/declarative/kong.yaml"  # Mantido porque estamos em DB-less.
            - name: KONG_PROXY_ACCESS_LOG
              value: "/dev/stdout"
            - name: KONG_ADMIN_ACCESS_LOG
              value: "/dev/stdout"
            - name: KONG_PROXY_ERROR_LOG
              value: "/dev/stderr"
            - name: KONG_ADMIN_ERROR_LOG
              value: "/dev/stderr"
            - name: KONG_ADMIN_LISTEN
              value: "0.0.0.0:8001"
            - name: KONG_ADMIN_GUI_URL
              value: "http://localhost:8002"
          volumeMounts:
            - name: kong-config
              mountPath: "/kong/declarative/kong.yaml"
              subPath: "kong.yaml"  # Especifica o subPath dentro do ConfigMap.
      volumes:
        - name: kong-config
          configMap:
            name: kong-config  # Agora usa um ConfigMap para armazenar o kong.yaml.

---

apiVersion: v1
kind: Service
metadata:
  name: kong-service
spec:
  type: LoadBalancer  # Mantido para expor o Kong externamente.
  selector:
    app: kong
  ports:
    - name: proxy
      port: 8000
      targetPort: 8000
    - name: admin
      port: 8001
      targetPort: 8001
    - name: gui
      port: 8002
      targetPort: 8002
    - name: proxy-ssl
      port: 8443
      targetPort: 8443
    - name: admin-ssl
      port: 8444
      targetPort: 8444

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: kong-config
  labels:
    app: kong
# O arquivo kong.yaml deve ser criado e incluído manualmente neste ConfigMap.
# Execute: kubectl create configmap kong-config --from-file=kong.yaml
