apiVersion: v1
kind: ConfigMap
metadata:
  name: kong-config
  namespace: kong
data:
  KONG_DATABASE: "postgres"
  KONG_PG_HOST: "kong-db-postgres"
  KONG_PG_DATABASE: "kong-db-postgres"
  KONG_PG_USER: "kong"
  KONG_PG_PASSWORD: "kong"
  KONG_DECLARATIVE_CONFIG: "/kong/declarative/kong.yaml"
  KONG_PROXY_ACCESS_LOG: "/dev/stdout"
  KONG_ADMIN_ACCESS_LOG: "/dev/stdout"
  KONG_PROXY_ERROR_LOG: "/dev/stderr"
  KONG_ADMIN_ERROR_LOG: "/dev/stderr"
  KONG_ADMIN_LISTEN: "0.0.0.0:8001"
  KONG_ADMIN_GUI_URL: "http://localhost:8002"
