  apiVersion: v1
kind: Service
metadata:
  name: kong-service
  namespace: kong
spec:
  selector:
    app: kong
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
    - protocol: TCP
      port: 8443
      targetPort: 8443
    - protocol: TCP
      port: 8001
      targetPort: 8001
    - protocol: TCP
      port: 8444
      targetPort: 8444
    - protocol: TCP
      port: 8002
      targetPort: 8002
    - protocol: TCP
      port: 8445
      targetPort: 8445
    - protocol: TCP
      port: 8003
      targetPort: 8003
    - protocol: TCP
      port: 8004
      targetPort: 8004
  type: LoadBalancer
